build: false

environment:
  matrix:

    - PYTHON: "C:\\Python35"
      PYTHON_VERSION: "3.5.2"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python35"
      PYTHON_VERSION: "3.5.2"
      PYTHON_ARCH: "64"



init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - "%PYTHON%/python.exe setup.py install"

test_script:
  - "cd csv2vcf"
  - "%PYTHON%/python.exe -m csv2vcf contact.csv"
  - "cd VCF_CONVERT_contact"
  - "ls"